"""Allow nullables for Bio model

Revision ID: 13e103b28dbc
Revises: 1b0f7c8f670f
Create Date: 2024-11-14 19:41:59.584807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e103b28dbc'
down_revision: Union[str, None] = '1b0f7c8f670f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bios', 'latitude',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('bios', 'longitude',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('bios', 'profile_region',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('bios', 'profile_country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bios', 'profile_country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bios', 'profile_region',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bios', 'longitude',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('bios', 'latitude',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
