"""Add region, country attributes to Bio model

Revision ID: 18bf7f8b98fe
Revises: 38642bb0a019
Create Date: 2024-11-14 00:58:59.372384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bf7f8b98fe'
down_revision: Union[str, None] = '38642bb0a019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bios', sa.Column('profile_region', sa.String(length=50), nullable=False))
    op.add_column('bios', sa.Column('profile_country', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bios', 'profile_country')
    op.drop_column('bios', 'profile_region')
    # ### end Alembic commands ###
