"""Add relationships between Bio model and SearchFilter model

Revision ID: 1b0f7c8f670f
Revises: ff79db5645c4
Create Date: 2024-11-14 17:27:30.399601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0f7c8f670f'
down_revision: Union[str, None] = 'ff79db5645c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendships_search_filter', 'search_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('friendships_search_filter_bio_id_fkey', 'friendships_search_filter', type_='foreignkey')
    op.create_foreign_key(None, 'friendships_search_filter', 'bios', ['bio_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships_search_filter', type_='foreignkey')
    op.create_foreign_key('friendships_search_filter_bio_id_fkey', 'friendships_search_filter', 'bios', ['bio_id'], ['id'])
    op.alter_column('friendships_search_filter', 'search_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
