"""Add BioPhoto, Like models

Revision ID: 2d6021a0c98b
Revises: edbca894a74a
Create Date: 2024-11-13 19:22:34.047662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6021a0c98b'
down_revision: Union[str, None] = 'edbca894a74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bios_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bio_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['bio_id'], ['bios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('like_sender_bio_id', sa.Integer(), nullable=False),
    sa.Column('like_receiver_bio_id', sa.Integer(), nullable=False),
    sa.Column('is_match', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['like_receiver_bio_id'], ['bios.id'], ),
    sa.ForeignKeyConstraint(['like_sender_bio_id'], ['bios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('bios_photos')
    # ### end Alembic commands ###
