"""Add reference bio_id and search_id for FriendshipSearchFilter

Revision ID: 71e873ddb8b6
Revises: 18bf7f8b98fe
Create Date: 2024-11-14 11:33:27.652280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e873ddb8b6'
down_revision: Union[str, None] = '18bf7f8b98fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships_search_filter', sa.Column('bio_id', sa.Integer(), nullable=False))
    op.add_column('friendships_search_filter', sa.Column('search_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'friendships_search_filter', 'bios', ['bio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships_search_filter', type_='foreignkey')
    op.drop_column('friendships_search_filter', 'search_id')
    op.drop_column('friendships_search_filter', 'bio_id')
    # ### end Alembic commands ###
