"""gender nullable for search filter

Revision ID: ff79db5645c4
Revises: 71e873ddb8b6
Create Date: 2024-11-14 13:04:46.474557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff79db5645c4'
down_revision: Union[str, None] = '71e873ddb8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendships_search_filter', 'gender',
               existing_type=postgresql.ENUM('MAN', 'WOMAN', 'BOTH', 'OTHER', name='gender_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendships_search_filter', 'gender',
               existing_type=postgresql.ENUM('MAN', 'WOMAN', 'BOTH', 'OTHER', name='gender_enum'),
               nullable=False)
    # ### end Alembic commands ###
